### ISSUE TITLE
White scroll bars appear in dark mode in Blink on macOS 

### ISSUE THREAD

**Issue by danielledeleo** [nginx/nginx.org#49]
Edge on macOS (system dark mode, Show scroll bars set to: _Automatic based on mouse or trackpad_):

<img width="1277" alt="Screenshot 2024-07-11 at 11 00 17 AM" src="https://github.com/nginx/nginx.org/assets/667598/0ebf61ef-941a-4b5d-938a-b06460304650">

In Firefox, the issue is less apparent, but still present.

<img width="1477" alt="Screenshot 2024-07-11 at 1 01 11 PM" src="https://github.com/nginx/nginx.org/assets/667598/20f0bd09-9204-4962-bf96-cdc78ed551cb">

<details>
<summary>Light mode screenshots (scroll bars also visible):</summary>

Chrome/Edge:
<img width="1477" alt="Screenshot 2024-07-11 at 1 40 30 PM" src="https://github.com/nginx/nginx.org/assets/667598/9f92f353-8e0e-4e04-b9d8-c792a872eea9">

Firefox:
<img width="1477" alt="Screenshot 2024-07-11 at 1 41 48 PM" src="https://github.com/nginx/nginx.org/assets/667598/1912de7b-94dd-4c3c-99c8-8043a95d5464">

</details>

On mobile (iOS, Safari), where title overflow is most relevant, the current CSS `overflow-x: scroll;` rule works elegantly. Scroll bars only appear when in use.

<img width="400" alt="IMG_2449" src="https://github.com/nginx/nginx.org/assets/667598/983ab0fa-4e40-420d-aeb2-367e07983ca1">

**Comment by danielledeleo** [comment]
The simplest visual fix for desktop would be:

```diff
 h2 {
     font-size: 2rem;
     line-height: 2.25rem;
     margin: 1rem 0 .5rem 0;
     overflow-x: scroll;
+    scrollbar-width: none;
 }
```

**Comment by lcrilly** [comment]
Hi @danielledeleo - thanks for the report. I want to see if we can solve this with the `overflow` behavior before resorting to hiding the scrollbar.

Is that something you can take a look at?

**Comment by danielledeleo** [comment]
> Hi @danielledeleo - thanks for the report. I want to see if we can solve this with the `overflow` behavior before resorting to hiding the scrollbar.
> 
> Is that something you can take a look at?

That was my first impulse as well. Note that even today, the horizontal scrollbars aren't displayed at all in Safari on iOS until you touch the scroll area, and the proposed CSS fix doesn't change that behaviour. I don't have an Android device to test, on unfortunately.

The worst case comes from long titles that don't break on spaces, like `ngx_http_proxy_protocol_vendor_module`. Breaking on underscores would be better, but that requires modifying titles:

```html
 <h2>Module ngx<wbr/>_http<wbr/>_proxy<wbr/>_protocol<wbr/>_vendor<wbr/>_module</h2>
```

---

I think this is a great solution. Here's what it looks like with `<wbr/>` tags injected in the browser inspector:

<img width="746" alt="Screenshot 2024-07-23 at 4 57 01 PM" src="https://github.com/user-attachments/assets/706a21ac-ae31-4282-b0f6-41c07f3e34b9">

---

Manual `<wbr>` is preferable to `word-break: break-all;` to avoid situations like this:

<img width="637" alt="Screenshot 2024-07-23 at 4 58 24 PM" src="https://github.com/user-attachments/assets/0c4a3d4c-2c44-49c7-9559-522986c6bfad">

---

## Conclusion

I tried to get it working by injecting them at the XSLT level (it has been about 10 years since I last wrote XSLT), but the bespoke XSLS pre-processor seems to be extremely picky and lacking in features. If someone more familiar with this XSLS dialect wants to give it a shot, go for it. I can't commit to a fix at this time.

**Comment by lcrilly** [comment]
We do get `translate()` though… but it only transforms a single character so we can't insert a tag.

Here's a horrible hack:
```diff
diff --git a/xsls/body.xsls b/xsls/body.xsls
index d6010842..212fa57b 100644
--- a/xsls/body.xsls
+++ b/xsls/body.xsls
@@ -43,7 +43,8 @@ X:template body (lang) {
 
     <div id="content">
         <h2>
-        !{@name} X:if "$YEAR" { X:text{: } !{$YEAR} }
+        !{translate(@name, '_', '﹏')}
+        X:if "$YEAR" { X:text{: } !{$YEAR} }
         </h2>
 
         X:if "$ORIGIN and document(concat($XML, '/', $ORIGIN))/*/@rev and
diff --git a/css/style_en.css b/css/style_en.css
index 663923b7..85fa664d 100644
--- a/css/style_en.css
+++ b/css/style_en.css
@@ -66,7 +66,6 @@ h2 {
     font-size: 2rem;
     line-height: 2.25rem;
     margin: 1rem 0 .5rem 0;
-    overflow-x: scroll;
 }

 h4 {
```

 
![Screenshot 2024-07-24 at 16 34 33](https://github.com/user-attachments/assets/9d28a276-64ed-45c9-a26b-fc7286b466ae)
